// <auto-generated />
namespace ServiceBooking.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version5));
        
        string IMigrationMetadata.Id
        {
            get { return "201704171657420_Version5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
